### ISSUE TITLE
Uncaught ReferenceError: fileEvelts is not defined

### ISSUE THREAD

**Issue by carloscarcamo** [rwatts3/atom-ide-json#10]
[Enter steps to reproduce:]

1. Open json file
2. Save file

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.3
**Thrown From**: [ide-json](https://github.com/atom/ide-json) package 0.2.1

### Stack Trace

Uncaught ReferenceError: fileEvelts is not defined

```
At /Users/ccarcamo/.atom/packages/ide-json/node_modules/atom-languageclient/build/lib/server-manager.js:277

ReferenceError: fileEvelts is not defined
    at ServerManager.projectFilesChanged (/packages/ide-json/node_modules/atom-languageclient/build/lib/server-manager.js:277:31)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at didChangeCallback (/Applications/Atom.app/Contents/Resources/app/src/project.js:381:28)
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:533:13)
    at sub.native.onDidChange.events (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:436:64)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at NSFWNativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:167:24)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:276:18)
```

### Commands

```
  2x -4:36.9.0 core:delete (input.hidden-input)
     -4:36.1.0 core:move-down (input.hidden-input)
     -4:35.8.0 editor:consolidate-selections (input.hidden-input)
     -4:35.8.0 core:cancel (input.hidden-input)
  3x -4:35.6.0 core:move-down (input.hidden-input)
     -4:34.1.0 core:move-left (input.hidden-input)
  2x -4:33.7.0 core:delete (input.hidden-input)
     -4:32.9.0 autocomplete-plus:cancel (input.hidden-input)
     -4:32.4.0 core:save (input.hidden-input)
     -3:34.3.0 core:delete (input.hidden-input)
  2x -3:34 core:save (input.hidden-input)
     -3:25 core:undo (input.hidden-input)
     -3:22.6.0 core:delete (input.hidden-input)
  5x -3:22.1.0 core:save (input.hidden-input)
     -1:31 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:11.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-html-preview 0.2.5 
atom-ide-ui 0.12.0 
atom-typescript 12.6.1 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
color-picker 2.3.0 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
gpp-compiler 3.0.7 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-python 1.0.0 
ide-rust 0.17.1 
ide-typescript 0.7.6 
ide-yaml 0.4.3 
intentions 1.1.5 
language-babel 2.85.0 
language-docker 1.1.8 
language-ejs 0.4.0 
language-rust 0.4.12 
linter 2.2.0 
linter-docker 0.3.2 
linter-gcc 0.7.1 
linter-js-yaml 1.3.0 
linter-ui-default 1.7.1 
pigments 0.40.2 
react-snippets 1.1.1 
script 3.18.1 
```

**Comment by rsese** [comment]
Thanks for the report - does this happen for any .json file or just a particular one?

**Comment by carloscarcamo** [comment]
Yes, for any .json file.
