### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by kognise** [rwatts3/atom-ide-json#11]
[Enter steps to reproduce:]

I don't know, this just popped up. Sorry if this is useless :D

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-json](https://github.com/atom/ide-json) package 0.2.1

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\felix\.atom\packages\ide-json\node_modules\vscode-jsonrpc\lib\messageReader.js:68

Error: Message header must separate key and value using :
    at /packages/ide-json/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/packages/ide-json/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/packages/ide-json/node_modules/vscode-jsonrpc/lib/messageReader.js:194:43)
    at /packages/ide-json/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
  5x -4:49.8.0 core:save (input.hidden-input)
     -3:49.3.0 core:move-right (input.hidden-input)
     -3:47.5.0 core:save (input.hidden-input)
  2x -3:41 core:backspace (input.hidden-input)
     -3:38.6.0 core:save (input.hidden-input)
     -3:32.8.0 core:backspace (input.hidden-input)
     -3:31.9.0 core:save (input.hidden-input)
     -3:30 editor:newline (input.hidden-input)
     -3:27.7.0 core:save (input.hidden-input)
     -3:26.2.0 editor:newline (input.hidden-input)
     -3:24.2.0 core:save (input.hidden-input)
     -3:01.9.0 core:backspace (input.hidden-input)
  2x -3:00.6.0 core:save (input.hidden-input)
     -0:50.8.0 core:paste (input.hidden-input)
  3x -0:46.2.0 core:backspace (input.hidden-input)
     -0:17.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
file-type-icons 1.3.4 
ide-css 0.3.0 
ide-ember 0.4.2 
ide-go 0.12.3 
ide-html 0.4.2 
ide-json 0.2.1 
ide-php 0.7.15 
ide-python 1.0.0 
ide-typescript 0.7.6 
ide-yaml 0.4.4 
language-batch 0.4.0 
platformio-ide-terminal 2.8.4 
styri-syntax 0.2.0 
teletype 0.13.3 
```

**Comment by kognise** [comment]
Nvm I'm stupid my mistake :) oops
