### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by pureapplikationen** [rwatts3/atom-ide-json#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [ide-json](https://github.com/atom/ide-json) package 0.2.0

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/admin/.atom/packages/ide-json/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-json/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-json/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-json/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:365:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:137:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/src/text-editor.js:590:26)
    at Function.module.exports.Emitter.simpleDispatch (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:819:26)
    at DisplayLayer.didChange (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:814:57)
    at languageModeDisposable.buffer.languageMode.onDidChangeHighlighting (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:157:18)
    at Function.module.exports.Emitter.simpleDispatch (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextMateLanguageMode.tokenizeNextChunk (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/src/text-mate-language-mode.js:307:26)
    at _.defer (/Users/admin/Downloads/Atom 2.app/Contents/Resources/app/src/text-mate-language-mode.js:274:63)
    at /Users/admin/Downloads/Atom 2.app/Contents/Resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -8:52 editor:toggle-line-comments (input.hidden-input)
     -8:50.6.0 core:save (input.hidden-input)
     -1:41 snippets:next-tab-stop (input.hidden-input)
     -1:41 snippets:expand (input.hidden-input)
     -1:41 editor:indent (input.hidden-input)
     -1:36.9.0 core:move-right (input.hidden-input)
     -1:34.5.0 core:backspace (input.hidden-input)
     -1:32.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:30.5.0 core:save (input.hidden-input)
     -1:19.1.0 editor:newline (input.hidden-input)
     -1:15.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-format 1.0.8 
atom-handlebars 1.3.0 
atom-ide-ui 0.7.2 
autocomplete-javascript 0.0.2 
ember-cli-helper 0.17.1 
formatter 2.12.4 
git-control 0.9.0 
git-plus 7.10.0 
ide-css 0.2.0 
ide-html 0.4.1 
ide-json 0.2.0 
ide-typescript 0.7.2 
ide-yaml 0.4.2 
language-csv 1.1.2 
language-emblem 0.2.0 
language-qml 1.0.0 
pretty-json 1.6.4 
rubo-format 0.4.1 
```

**Comment by rsese** [comment]
Thanks for the report - do you remember what you were doing when you saw the error and if you can reproduce it?

I believe there's also some work being done so that if you run into an error like this, we'll try to restart...

**Comment by ZyanKLee** [comment]
I got the same error message.

```
Community Packages (36) ~/.atom/packages
├── aligner@1.2.4
├── aligner-javascript@1.3.0
├── aligner-puppet@0.1.1
├── atom-ide-ui@0.9.3
├── atom-npm@0.3.1
├── atom-terminal@0.8.0
├── atom-yamljson@0.2.4
├── browser-plus@0.0.98
├── busy-signal@1.4.3
├── column-select@1.0.1
├── formatter-gofmt@1.0.1
├── git-plus@7.10.0
├── gitlab-integration@0.4.6
├── go-plus@5.8.2
├── ide-docker@0.0.2
├── ide-go@0.7.0
├── ide-json@0.2.1
├── ide-php@0.7.9
├── ide-puppet@1.3.1
├── ide-yaml@0.4.2 (disabled)
├── intentions@1.1.5
├── language-markdown@0.25.1
├── language-puppet@0.23.0
├── language-restructuredtext@1.1.0
├── language-sphinx@0.1.6
├── language-terraform@0.8.1
├── linter@2.2.0 (disabled)
├── linter-golinter@1.2.2
├── linter-markdown@5.2.0
├── linter-puppet-lint@0.8.4
├── linter-rst@0.0.3
├── linter-ui-default@1.7.1
├── multi-cursor@2.1.5
├── npm-plus@0.4.0
├── save-autorun@0.3.3
└── terraform-fmt@0.3.0
```
I remember, I was saving a modified puppet module file. This is reproducable and occurs after some file editing, switching and saving different files.
When it occured, it will repeat its error message on each attempt at saving and even during writing of code. Saving the file is not possible anymore until atom is quit and started again.

**Comment by ZyanKLee** [comment]
The error still persists with atom `1.34.0`, for updated information see #12, #14 and #15

**Comment by storm49152** [comment]
I get this message frequently. I'm not doing anything special (like: I'm typing text, doing nothing else). I start Atom, and sometimes I get the popups (which happen with every char that I type) almost immediately, and sometimes it takes a while.
I also cannot save the document when this is happening. Luckily Atom keeps a copy of my changes..

**Comment by zacwitte** [comment]
I got this error on Atom 1.39.1 x64 on mac os x catalina.

**Comment by storm49152** [comment]
Is there any news on this? Quite some time ago I uninstalled all ide-* packages because it's unworkable: every 5-10 minutes I get this error message for files that are not even JSON, and I have to restart Atom. Yesterday I tried again on Atom 1.41.0 (Linux) , and immediately I start receiving these errors again.
