### ISSUE TITLE
Uncaught Error: Connection is disposed.

### ISSUE THREAD

**Issue by ghost** [rwatts3/atom-ide-json#5]
1. Install both ide-python and ide-json package
2. Try to toggle pydocstyle option
Extra Info: I don't know if it's the same error but it also happened with I believe ide-typescript

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.4
**Thrown From**: [ide-json](https://github.com/atom/ide-json) package 0.2.1

### Stack Trace

Uncaught Error: Connection is disposed.

```
At /home/sshehriyar/.atom/packages/ide-json/node_modules/vscode-jsonrpc/lib/main.js:616

Error: Connection is disposed.
    at /packages/ide-json/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-json/node_modules/vscode-jsonrpc/lib/main.js:616:19)
    at Object.sendNotification (/packages/ide-json/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:341:19)
    at LanguageClientConnection.didChangeConfiguration (/packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:120:14)
    at _disposable.add.atom.config.observe (/packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:263:36)
    at onDidChangeKeyPath.event (/usr/share/atom/resources/app/src/config.js:1013:60)
    at emitter.on (/usr/share/atom/resources/app/src/config.js:1023:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:1175:62)
    at Config.setRawValue (/usr/share/atom/resources/app/src/config.js:1008:23)
    at Config.set (/usr/share/atom/resources/app/src/config.js:711:18)
    at SettingsPanel.set (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:238:34)
    at HTMLInputElement.changeHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:174:25)
```

### Commands

```
     -1:27.9.0 minimap:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui.teletype-Authenticated)
     -1:27.6.0 zen:toggle (input.hidden-input)
     -1:27.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui.teletype-Authenticated)
     -1:27.2.0 pane:show-next-recently-used-item (input.hidden-input)
     -1:27 pane:move-active-item-to-top-of-stack (div.package-detail.panels-item)
     -1:26.3.0 pane:show-next-recently-used-item (input#Zen.minimap.input-checkbox)
     -1:26.2.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -1:25.2.0 zen:toggle (input.hidden-input)
     -1:25.2.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui.teletype-Authenticated)
     -1:24.8.0 zen:toggle (input.hidden-input)
     -1:24.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui.teletype-Authenticated)
  2x -1:23 core:close (input.hidden-input)
     -1:17.5.0 pane:show-next-recently-used-item (input#Zen.minimap.input-checkbox)
     -1:17.3.0 pane:move-active-item-to-top-of-stack (input#Zen.minimap.input-checkbox)
  3x -1:13.8.0 core:close (input.hidden-input)
     -1:02.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui.teletype-Authenticated)
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
dracula-syntax 2.0.6 
dracula-ui 0.6.0 
file-icons 2.1.18 
highlight-selected 0.13.1 
Hydrogen 2.3.0 
ide-json 0.2.1 
ide-python 0.9.1 
ide-typescript 0.7.6 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
platformio-ide-terminal 2.8.1 
teletype 0.10.0 
Zen 0.18.0 
```

**Comment by ghost** [comment]
I have no idea but now it's gone. There must be something I might have done cuz the error kept popping up upon toggling any option of any package :smile:
