### ISSUE TITLE
Failed to load the ide-json package

### ISSUE THREAD

**Issue by ghost** [rwatts3/atom-ide-json#7]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-json](https://github.com/atom/ide-json) package 0.2.1

### Stack Trace

Failed to load the ide-json package

```
At Unexpected identifier

SyntaxError: Unexpected identifier
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/ide-json/node_modules/atom-languageclient/build/lib/main.js:1:106)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/ide-json/lib/main.js:1:109)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
```

### Commands

```
     -0:22.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:20.9.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-json-color 0.6.0 
atom-live-server 2.3.0 
browser-plus 0.0.98 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
ide-json 0.2.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Do you remember what you were doing at the time of the error?  Also, is the error is reproducible?
